# Generated by Django 4.2.7 on 2024-03-05 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_reviewrattings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRattings',
            new_name='ReviewRatings',
        ),
    ]
