# Generated by Django 4.2.7 on 2024-03-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_reviewratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewratings',
            name='rating',
            field=models.FloatField(),
        ),
    ]
