# Generated by Django 5.0.3 on 2024-03-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgalary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGalary',
            new_name='ProductGalery',
        ),
        migrations.AlterModelOptions(
            name='productgalery',
            options={'verbose_name': 'productgalery', 'verbose_name_plural': 'Product Galery'},
        ),
    ]
